name 'test-clickhouse'
maintainer 'Vinted'
maintainer_email 'sre@vinted.com'
license 'MIT'
description 'Installs/Configures test-clickhouse'
version '0.2.0'
chef_version '>= 12.1'

depends 'clickhouse'
depends 'java', '~> 11.1.0'
